import os

LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO")

DROPBOX_ACCESS_TOKEN = os.environ["DROPBOX_ACCESS_TOKEN"]
DROPBOX_ROOT_FOLDER = os.environ["DROPBOX_ROOT_FOLDER"]

IFQ_USERNAME = os.environ["IFQ_USERNAME"]
IFQ_PASSWORD = os.environ["IFQ_PASSWORD"]

SLACK_WEBHOOK_URL = os.environ["SLACK_WEBHOOK_URL"]
SLACK_SIGNING_SECRET = os.environ["SLACK_SIGNING_SECRET"]

TELEGRAM_TOKEN = os.environ["TELEGRAM_TOKEN"]
TELEGRAM_DEFAULT_GROUP_ID = os.environ["TELEGRAM_DEFAULT_GROUP_ID"]

TOGGL_WORKSPACE_ID = os.environ["TOGGL_WORKSPACE_ID"]
TOGGL_USER_AGENT = os.environ["TOGGL_USER_AGENT"]
TOGGL_API_TOKEN = os.environ["TOGGL_API_TOKEN"]

SNS_COMMANDS_TOPIC_ARN = os.environ["SNS_COMMANDS_TOPIC_ARN"]
